### ISSUE TITLE
Would back translation improve the translation result?

### ISSUE THREAD

**Issue by leminhyen2** [MorinoseiMorizo/jparacrawl-finetune#6]
I want to adapt Jpara to be more casual/conversational by using dataset like JESC. 

However, beside that and Open Sub, parallel dataset for conversational is seriously lacking. I'm thinking of mining Japanese sentences and back-translate it to English using Jpara model then include it in the training or fine-tuning process. 

Do you think this strategy can improve the translation quality of JAP to ENG?

**Comment by MorinoseiMorizo** [comment]
Hi, 
Yes, we don't have enough conversational parallel corpora, and I think your strategy would improve translation quality.
In the machine translation research community, adapting the model to the specific domain is called domain adaptation.
Back-translating the target domain monolingual data is one of the major methods, and you might want to find other methods described in this survey paper.
https://arxiv.org/abs/1806.00258

If you collect monolingual data, I recommend you to mine **English** sentences, since collecting the target side would help more than collecting the source side.

If you have other questions, please feel free to ask me.
Thanks!

**Comment by leminhyen2** [comment]
Thanks you! that's very helpful information

I'm trying to make the model suitable for visual novel translation and since I'm still a newbie in deep learning, sometimes it can be quite confusing.
